spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rewards
    password: password
    username: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect